print("----------------------------Zad1----------------------------")
print("ax^2 + bx + c = 0")
a = int(input(" Print a: "))
b = int(input(" Print b: "))
c = int(input(" Print c: "))
d = (b ** 2 - 4 * a * c)
print("D > 0 =", d > 0)
print("----------------------------Zad2----------------------------")
w1 = input(" Please type first word: ").lower()
w2 = input(" Please type second word: ").lower()
w1 = w1.replace('a', "7").replace('e', "7").replace('y', "7").replace('u', "7").replace('i', "7").replace('o', "7")
print(w1)

cons = ['q', 'w', 'r', 't', 'p', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm']
for c in cons:
    w2 = w2.replace(c, '6')
print(w2)
print("Concat = " + w1 + w2)
print("----------------------------Zad3----------------------------")
bin = input("Please write number in binary: ")
oct = input("Please write number in octal: ")
hex = input("Please write number in hexadecimal: ")
print("Variable {0} has value {1} and was conversed into {2} ".format("bin", bin, int(bin, 2)))
print("Variable {0} has value {1} and was conversed into {2} ".format("oct", oct, int(oct, 8)))
print("Variable {0} has value {1} and was conversed into {2} ".format("hex", hex, int(hex, 16)))
